version: '3'

volumes:
  nfs_YYLUI:
    driver_opts:
      type: nfs
      o: "addr=${NAS_SERVER_IP},nolock,soft,rw"
      device: ":/volume1/backend/project/YYLUI"

services:
  kali:
    image: yenyinglu/kali
    restart: always
    hostname: "kali"
    privileged: true
    tty: true
    ports:
      - "20022:22"
      - "23389:3389"
      - "28000:8000"
      - "24444:4444"
    container_name: kali
    volumes:
      - nfs_YYLUI:/root/cyberScript
    command: >
      /bin/bash -c "
        sysctl -w net.ipv6.conf.all.disable_ipv6=0 &&
        service ssh start &&
        service xrdp restart &&
        tail -f /dev/null"
    networks:
      - backend_net

networks:
  backend_net: