version: '3'

volumes:

  nfs_mariadb:
    driver_opts:
      type: nfs
      o: "addr=${NAS_SERVER_IP},nolock,soft,rw"
      device: ":/volume1/backend/storage/mariadb"


services:

  mariadb:
    image: mariadb
    ports:
      - 10370:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - nfs_mariadb:/var/lib/mysql
    networks:
      - backend_net
    user: "1024"

networks:
  backend_net: