version: '3'

volumes:
  nfs_minIO:
    driver_opts:
      type: nfs
      o: "addr=192.168.100.145,nolock,soft,rw"
      device: ":/volume1/backend/storage/minIO"

services:

  minio:
    image: minio/minio
    hostname: "minio"
    ports:
      - 10900:9000
      - 10831:9090
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - nfs_minIO:/data
    command: server /data --console-address ":9090"
    networks:
      - backend_net
    restart: always

networks:
  backend_net: