volumes:
  nfs_nginx:
    driver_opts:
      type: nfs
      o: "addr=${NAS_SERVER_IP},nolock,soft,rw"
      device: ":/volume1/backend/project/YYLUI/IAC-DockerCompose/nginx"

services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "443:443"
    networks:
      - backend_net
    volumes:
      - nfs_nginx:/mnt/nginx_conf
    command: >
      /bin/bash -c "cp -r /mnt/nginx_conf/* /etc/nginx/conf.d/ && nginx -g 'daemon off;'"
    extra_hosts:
      - "dashboard.mydormroom.com:${HOST_DOCKER_INTERNAL}"
      - "argocd.mydormroom.com:${HOST_DOCKER_INTERNAL}"
      - "adminer.mydormroom.com:${HOST_DOCKER_INTERNAL}"
      - "grafana.mydormroom.com:${HOST_DOCKER_INTERNAL}"
      - "open-webui.mydormroom.com:${HOST_DOCKER_INTERNAL}"
    restart: always

networks:
  backend_net: