volumes:
  nfs_conf:
    driver_opts:
      type: nfs
      o: "addr=${NAS_SERVER_IP},nolock,soft,rw"
      device: ":/volume1/backend/project/YYLUI/IAC-DockerCompose/nginx"

services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "443:443"
    networks:
      - backend_net
    volumes:
      - nfs_conf:/etc/nginx
    extra_hosts:
      - "dashboard.mydormroom.com:${HOST_DOCKER_INTERNAL}"
    restart: always

networks:
  backend_net: