version: '3'

volumes:
  nfs_conf:
    driver_opts:
      type: nfs
      o: "addr=192.168.100.145,nolock,soft,rw"
      device: ":/volume1/backend/privateCloud/config"

services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "10802:80"
    networks:
      - backend_net
    volumes:
      - nfs_conf:/mnt
    restart: always

networks:
  backend_net: