version: '3'

volumes:
  nfs_chieh:
    driver_opts:
      type: nfs
      o: "addr=192.168.100.145,nolock,soft,rw"
      device: ":/volume1/backend/project/chieh"

  nfs_vscode_config:
    driver_opts:
      type: nfs
      o: "addr=192.168.100.145,nolock,soft,rw"
      device: ":/volume1/backend/compiler/vscode/config" 

services:
  vscode-chieh:
    image: yenyinglu/vscode
    container_name: vscode-chieh
    hostname: "vscode-chieh"
    ports:
      - "127.0.0.1:30812:8090"
      - "127.0.0.1:30104:3000"
    volumes:
      - nfs_chieh:/home/coder/project
      - nfs_vscode_config:/home/coder/.config/code-server
    environment:
      - WATCHPACK_POLLING=true
      - PASSWORD=${VSCODE_CHIEH_PASSWORD}
    command: ["code-server", "--auth", "password", "--disable-telemetry", "--bind-addr", "0.0.0.0:8090"]
    networks:
      - backend_net
    restart: always

networks:
  backend_net:

