version: '3'

volumes:
  nfs_qiao:
    driver_opts:
      type: nfs
      o: "addr=192.168.100.145,nolock,soft,rw"
      device: ":/volume1/backend/project/qiao"

  nfs_vscode_config:
    driver_opts:
      type: nfs
      o: "addr=192.168.100.145,nolock,soft,rw"
      device: ":/volume1/backend/compiler/vscode/config" 

services:
  vscode-qiao:
    image: yenyinglu/vscode
    container_name: vscode-qiao
    hostname: "vscode-qiao"
    ports:
      - "30811:8090"
      - "30103:3000"
    volumes:
      - nfs_qiao:/home/coder/project
      - nfs_vscode_config:/home/coder/.config/code-server
    environment:
      - WATCHPACK_POLLING=true
      - PASSWORD=${VSCODE_QIAO_PASSWORD}
    command: ["code-server", "--auth", "password", "--disable-telemetry", "--bind-addr", "0.0.0.0:8090"]
    networks:
      - backend_net
    restart: always

networks:
  backend_net:

