[[proxies]]
name = "minio"
type = "https"
localIP = "nginx"
localPort = 443
customDomains = ["minio.mydormroom.dpdns.org"]

[[proxies]]
name = "gitlab"
type = "https"
localIP = "nginx"
localPort = 443
customDomains = ["minio.mydormroom.dpdns.org"]
